# .github/workflows/reusable-infisical-fetch.yml
name: Infisical Fetch

on:
  workflow_call:

env:
  INFISICAL_IDENTITY_ID: '8977b274-e440-4612-9097-69faf3ecbe2a'
  INFISICAL_ENV_SLUG: 'prod'
  INFISICAL_SECRETS_PROJECT_ID: 'Secrets'

jobs:
  fetch-and-run:
    runs-on: [self-hosted, linux, infra]
    # Required for OIDC authentication
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Connects to Infisical and injects secrets as environment variables
      - name: Fetch Secrets from Infisical
        uses: Infisical/secrets-action@v1
        with:
          client-id: ${{ env.INFISICAL_IDENTITY_ID }}
          env-slug: ${{ env.INFISICAL_ENV_SLUG }}
          project-id: ${{ env.INFISICAL_SECRETS_PROJECT_ID }}
          # Specifying OIDC means no static client-secret is needed
          auth-method: 'oidc'
          export-type: 'file'
          file-path: '.env'
